WIDTH_WINDOW = 4000
HEIGHT_WINDOW = 4000

WIDTH_SERVER_WIND = 300
HEIGHT_SERVER_WIND = 300



FOODS_RADIUS = 15

BOTS_QUANTITY = 25
FOODS_QUANTITY = round((WIDTH_WINDOW*HEIGHT_WINDOW)//100000)

PLAYER_DEFAULT_HEIGHT_WINDOW = 500
PLAYER_DEFAULT_WIDTH_WINDOW = 1000

PLAYER_RADIUS = 50
FPS = 100
PLAYER_COLOURS = ['green', 'red', 'blue', 'yellow', 'purple', 'white', 'brown']
